"""change_firma_base64_to_longtext

Revision ID: 1234567890ab
Revises: e10ab9da66b7
Create Date: 2025-11-19 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1234567890ab'
down_revision = 'e10ab9da66b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firmas', schema=None) as batch_op:
        batch_op.alter_column('firma_base64',
               existing_type=mysql.TEXT(),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firmas', schema=None) as batch_op:
        batch_op.alter_column('firma_base64',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
