"""Agregar columnas de auditoria SVG a modelo Firma

Revision ID: 8978b78c4852
Revises: 1234567890ab
Create Date: 2025-11-21 15:12:37.278075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8978b78c4852'
down_revision = '1234567890ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles_entrada_salida', schema=None) as batch_op:
        batch_op.alter_column('tipo_operacion',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='Tipo de operación: Entrada o Salida (puede ser NULL si está en borrador)',
               existing_nullable=True)
        batch_op.alter_column('motivo',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Motivo de la entrada/salida (puede ser NULL si está en borrador)',
               existing_nullable=True)
        batch_op.alter_column('accesorios_generales',
               existing_type=mysql.JSON(),
               type_=sa.String(length=200),
               existing_nullable=True)

    with op.batch_alter_table('firmas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firma_svg', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('timestamp_firma', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('hash_documento', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('consentimiento_aceptado', sa.Boolean(), nullable=True))
        batch_op.alter_column('firma_base64',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)

    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_funcionarios_estado'))
        batch_op.create_index(batch_op.f('ix_funcionarios_estado'), ['estado'], unique=False)

    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.alter_column('estado_completitud',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='Estado del movimiento: borrador, completo',
               existing_nullable=False,
               existing_server_default=sa.text("'completo'"))
        batch_op.drop_index(batch_op.f('idx_movimientos_estado_completitud'))
        batch_op.create_index(batch_op.f('ix_movimientos_estado_completitud'), ['estado_completitud'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimientos_estado_completitud'))
        batch_op.create_index(batch_op.f('idx_movimientos_estado_completitud'), ['estado_completitud'], unique=False)
        batch_op.alter_column('estado_completitud',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='Estado del movimiento: borrador, completo',
               existing_nullable=False,
               existing_server_default=sa.text("'completo'"))

    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_funcionarios_estado'))
        batch_op.create_index(batch_op.f('idx_funcionarios_estado'), ['estado'], unique=False)

    with op.batch_alter_table('firmas', schema=None) as batch_op:
        batch_op.alter_column('firma_base64',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
        batch_op.drop_column('consentimiento_aceptado')
        batch_op.drop_column('hash_documento')
        batch_op.drop_column('timestamp_firma')
        batch_op.drop_column('user_agent')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('firma_svg')

    with op.batch_alter_table('detalles_entrada_salida', schema=None) as batch_op:
        batch_op.alter_column('accesorios_generales',
               existing_type=sa.String(length=200),
               type_=mysql.JSON(),
               existing_nullable=True)
        batch_op.alter_column('motivo',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Motivo de la entrada/salida (puede ser NULL si está en borrador)',
               existing_nullable=True)
        batch_op.alter_column('tipo_operacion',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='Tipo de operación: Entrada o Salida (puede ser NULL si está en borrador)',
               existing_nullable=True)

    # ### end Alembic commands ###
