"""Convertir strings a DateTime y JSON

Revision ID: e10ab9da66b7
Revises: 860609728414
Create Date: 2025-11-11 16:30:41.117687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10ab9da66b7'
down_revision = '860609728414'
branch_labels = None
depends_on = None


def upgrade():
    # === INICIO DE CÓDIGO MANUAL PARA LIMPIEZA DE DATOS JSON ===
    op.execute("UPDATE activos SET atributos_dinamicos_json = '{}' WHERE atributos_dinamicos_json IS NULL OR atributos_dinamicos_json = ''")
    op.execute("UPDATE detalles_entrada_salida SET accesorios_generales = '{}' WHERE accesorios_generales IS NULL OR accesorios_generales = ''")
    op.execute("UPDATE detalles_entrega SET tipo_elementos = '{}' WHERE tipo_elementos IS NULL OR tipo_elementos = ''")
    op.execute("UPDATE detalles_traslado SET tipo_traslado_json = '{}' WHERE tipo_traslado_json IS NULL OR tipo_traslado_json = ''")
    op.execute("UPDATE detalles_traslado SET accesorios_generales_json = '{}' WHERE accesorios_generales_json IS NULL OR accesorios_generales_json = ''")
    op.execute("UPDATE mantenimientos SET atributos_reporte_json = '{}' WHERE atributos_reporte_json IS NULL OR atributos_reporte_json = ''")
    op.execute("UPDATE proveedores SET direccion = '' WHERE direccion IS NULL")
    # === FIN DE CÓDIGO MANUAL ===

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activos', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('atributos_dinamicos_json',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('fecha_ingreso_ajeno',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('auditoria_activos', schema=None) as batch_op:
        batch_op.alter_column('fecha_cambio',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('detalles_entrada_salida', schema=None) as batch_op:
        batch_op.alter_column('fecha_retorno_estimada',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('accesorios_generales',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('detalles_entrega', schema=None) as batch_op:
        batch_op.alter_column('fecha_oc_contrato',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('tipo_elementos',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('detalles_traslado', schema=None) as batch_op:
        batch_op.alter_column('fecha_traslado',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('tipo_traslado_json',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('accesorios_generales_json',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('mantenimientos', schema=None) as batch_op:
        batch_op.alter_column('fecha_mantenimiento',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('atributos_reporte_json',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('movimiento_documentos_adjuntos', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('fecha_aprobacion',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.alter_column('nit',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('direccion',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.alter_column('direccion',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('nit',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.alter_column('fecha_aprobacion',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('fecha',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('movimiento_documentos_adjuntos', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('mantenimientos', schema=None) as batch_op:
        batch_op.alter_column('atributos_reporte_json',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('fecha_mantenimiento',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('detalles_traslado', schema=None) as batch_op:
        batch_op.alter_column('accesorios_generales_json',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('tipo_traslado_json',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('fecha_traslado',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('detalles_entrega', schema=None) as batch_op:
        batch_op.alter_column('tipo_elementos',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('fecha_oc_contrato',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('detalles_entrada_salida', schema=None) as batch_op:
        batch_op.alter_column('accesorios_generales',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('fecha_retorno_estimada',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('auditoria_activos', schema=None) as batch_op:
        batch_op.alter_column('fecha_cambio',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('activos', schema=None) as batch_op:
        batch_op.alter_column('fecha_ingreso_ajeno',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('atributos_dinamicos_json',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
